kind: pipeline
type: docker
name: default

steps:
- name: build
  image: docker:latest
  commands:
  - mkdir .secret
  - echo "$USER" > .secret/user
  - echo "$TOKEN" > .secret/token
  - make
  - rm -rf .secret
